---
apiVersion: v1
kind: Service
metadata:
  name: wdumps
  namespace: tool-wdumps
  labels:
    name: wdumps
    toolforge: tool
    tools.wmflabs.org/webservice: "true"
    tools.wmflabs.org/webservice-version: "1"
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    name: wdumps
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    name: wdumps
    toolforge: tool
    tools.wmflabs.org/webservice: "true"
    tools.wmflabs.org/webservice-version: "1"
  name: wdumps
  namespace: tool-wdumps
spec:
  rules:
  - host: tools.wmflabs.org
    http:
      paths:
      - backend:
          serviceName: wdumps
          servicePort: 8000
        path: /wdumps(/|$)(.*) 
  - host: wdumps.toolforge.org
    http:
      paths:
       - backend:  
          serviceName: wdumps
          servicePort: 8000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-08-13T21:36:09Z
  generation: 2
  labels:
    name: wdumps
    toolforge: tool
    tools.wmflabs.org/webservice: "true"
    tools.wmflabs.org/webservice-version: "1"
  name: wdumps
  namespace: tool-wdumps
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wdumps
      toolforge: tool
  template:
    metadata:
      labels:
        name: wdumps
        toolforge: tool
        tools.wmflabs.org/webservice: "true"
        tools.wmflabs.org/webservice-version: "1"
    spec:
      containers:
      - command: [/data/project/wdumps/www/run.sh]
        image: docker-registry.tools.wmflabs.org/toolforge-python35-sssd-web:latest
        name: webservice
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 125m
            memory: 256Mi
        workingDir: /data/project/wdumps/
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 60
